Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,9 +23,14 @@ jobs:
         run: |
           cd apache-jmeter-5.6.3/bin
           ./jmeter -n -t ../../jmeter/test-plan.jmx -l results.jtl
+          if [ $? -ne 0 ]; then
+            echo "JMeter tests failed"
+            exit 1  # Laat de workflow mislukken als JMeter-tests mislukken
+          fi
         working-directory: ${{ github.workspace }}  # Werk vanuit de hoofdmap van de repository
 
       - name: Upload test results
+        if: success()  # Upload de testresultaten alleen als de JMeter-tests succesvol waren
         uses: actions/upload-artifact@v2
         with:
           name: jmeter-results
